status: wip
context: 
    socialItems:
        - content: Cardiff games tomorrow! Make sure you bring charging packs/cables for the inevitable Pok√©mon GO splurge!
          timeAgo: 12 minutes ago
        - content: Happy Bristol Pride @wearefest from the Severn Bronies!
          image: https://pbs.twimg.com/media/Cm7PDUOWIAA1TGf.jpg
          timeAgo: 2 hours ago
        - content: No meet this coming Saturday (9th) but a few of us will be attending Bristol Pride! Meet at Castle Park before 11am if interested! Otherwise, we'll be having a weekly on Friday, same time, same place.
          timeAgo: 5 days ago
