status: wip
context:
    socialLinks:
        twitter: https://twitter.com/severnbronies
        facebook: https://facebook.com/severnbronies
        tumblr: http://blog.severnbronies.co.uk/
        telegram: https://telegram.me/severnbronies
        discord: https://discordapp.com/invite/mD3QkbX
        github: https://github.com/severnbronies